### ISSUE TITLE
Wrong Value? 

### ISSUE THREAD

**Issue by Happyfeet01** [GabrielTavernini/Covid19Stats#11]
With the last update I see an different value. Is that correct? 

![Screenshot_20200930_053143_com gabriel covid19stats](https://user-images.githubusercontent.com/3295104/94640204-46473880-02de-11eb-9c89-5c6321edc7ea.jpg)

**Comment by GabrielTavernini** [comment]
Yes, thank you for letting me know, that was a bug in version 2.0.2 of the app and it was mentioned in the issue https://github.com/GabrielTavernini/Covid19Stats/issues/10. 
With the release of [2.1.0](https://github.com/GabrielTavernini/Covid19Stats/releases/tag/v2.1.0) the bug has been fixed. The new version will be available on FDroid in a couple of days.
