### ISSUE TITLE
The chart lines go under or cross the X=0 value if the count is 0 or near 0

### ISSUE THREAD

**Issue by MrHeating** [GabrielTavernini/Covid19Stats#13]
![Screenshot_20201005-131529](https://user-images.githubusercontent.com/22666602/95073655-827afe80-070d-11eb-96d3-6fd50e844c42.png)
I can see how you weren't accounting for that. At least it doesn't crash. Just looks weird and confusing.

**Comment by GabrielTavernini** [comment]
Thanks for letting me know, I knew that there was gonna be some overshooting but didn't think it was that much.
Anyway, the issue is now solved and the fix will be rolling out with the next release.
