### ISSUE TITLE
Freezing with date restriction AND irish data

### ISSUE THREAD

**Issue by uli-on** [GabrielTavernini/Covid19Stats#18]
Hi Gabriel,
I just remarked this issue of app freezing (an empty screen with light gray background colour) when I have the combination of a restricted time span applied to Ireland's data. It happens as well with one of the preset time spans as with self chosen ones, and Ireland is the only one among the European countries I loaded so far that makes the app freeze.

Edit: I can amend that it also needs to have both switches in the prefs turned on, "Always load charts" and "Default to daily view".

Android 6.0.1, btw, with app v2.2.0 from F-Droid.

**Comment by uli-on** [comment]
I could restrict the time span further: Any date > 2020_06_24 makes the app freeze when Ireland is selected.

**Comment by GabrielTavernini** [comment]
Hi, thanks for reporting the bug. 
Apparently it has to do with the daily charts of recovered people, I’ll look into it.

**Comment by uli-on** [comment]
In case this matters: 
One more find, Sweden, with date > 2020-09-05 (and both pref switches turned on, as mentioned above).

**Comment by GabrielTavernini** [comment]
Hi, in the latest release I've decided to change the recovered chart with the active cases one which I think gives more valuable insights and better represents the country's situations.

This change also happens to fix the issue that you reported.
