### ISSUE TITLE
F-droid?

### ISSUE THREAD

**Issue by JonnyTech** [GabrielTavernini/Covid19Stats#2]
@GabrielTavernini would you consider publishing this on [F-Droid](https://f-droid.org/)? We just lost the only [similar app](https://gitlab.com/fdroid/rfp/-/issues/1315) which was beung hosted on @IzzySoft's [repo](https://android.izzysoft.de/repo) (mentioning this because you provide a prebuilt apk that Izzy can host). I notice that you fixed the parsing issue that caused the other apps author to abandon their project.

**Comment by GabrielTavernini** [comment]
Yeah absolutely but I've never published anything to F-Droid so if you could walk me through the process I would appreciate it.

**Comment by JonnyTech** [comment]
Great! Details are at the [request for packaging](https://gitlab.com/fdroid/rfp) repo, the important requirements are [metadata](https://gitlab.com/fdroid/fdroiddata/blob/master/CONTRIBUTING.md) (see the ([quickstart](https://gitlab.com/fdroid/fdroiddata/-/blob/master/README.md#quickstart)). I have not done it but hopefully @IzzySoft can chime in as he has helped many others through the process.

**Comment by IzzySoft** [comment]
As @JonnyTech mentions: just file an issue at the RFP repo. If you wish, use the simple template (which is used by default), we take care for the rest then. Or use the drop-down to switch to the "full" one if you want to do the tech stuff yourself (we'll then fill any gaps and fix if something was wrong).

Before starting with that, may I suggest you implement [Fastlane file structure](https://gitlab.com/snippets/1895688) in your repo here (details behind the link), and then start [tagging your releases](https://github.com/GabrielTavernini/Covid19Stats/releases)?

**Comment by GabrielTavernini** [comment]
I did all you suggested to do and just [filed an issue at the RFP repo.](https://gitlab.com/fdroid/rfp/-/issues/1349)
Hope I did everything right and let me know if there is anything else I have to do.

**Comment by licaon-kter** [comment]
Please restart Tagging as versionName, eg: both `X.X.X` and not one `X.X` and  the other `X.X.X`

**Comment by JonnyTech** [comment]
Yay! It's finally on F-Droid: https://f-droid.org/en/packages/com.gabriel.covid19stats/

` Version 1.3.0 (4) - Added on 2020-06-04`

**Comment by JonnyTech** [comment]
Ah, the latest release is v1.6 so they are 3 versions behind with their builds :(
