### ISSUE TITLE
App crashes when switching from UK to USA and back to UK.

### ISSUE THREAD

**Issue by abdrysdale** [GabrielTavernini/Covid19Stats#9]
The app freezes on the country select list.

I've tested this with a handful of other combinations but it only seems to crash with this combinations.

Love the app, keep up the good work!

**Comment by GabrielTavernini** [comment]
So after a bit of debugging, I found out that the problem came from the absence of data about recovered patients in some countries. The bug has been fixed with the commit f8246d1a1069386f4481c7e4bdb0c2c9e4cd2750.
